# app.yaml
runtime: python311    # Gunakan Python 3.11 (terbaru & stabil)
# service:  wedding-puka
service:  wedding-satrio-umi

handlers:
  # 1. Sajikan index.html saat akses root "/"
  - url: /
    static_files: index.html
    upload: index.html
    secure: always

  - url: /admin-ganteng
    static_files: admin-ganteng.html
    upload: admin-ganteng.html
    secure: always

  # 2. Sajikan semua file statis lainnya (CSS, JS, gambar, dll.)
  - url: /(.*)
    static_files: \1
    upload: (.*)
    secure: always